/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function createWallet(input: CreateWalletInput): WalletResult

export interface CreateWalletInput {
  password: string
  name?: string
  passwordHint?: string
  network?: string
  entropy?: string
}

export declare function importWalletMnemonic(input: ImportWalletMnemonicInput): WalletResult

export interface ImportWalletMnemonicInput {
  mnemonic: string
  password: string
  name?: string
  passwordHint?: string
  network?: string
}

export declare function importWalletPrivateKey(input: ImportWalletPrivateKeyInput): WalletResult

export interface ImportWalletPrivateKeyInput {
  privateKey: string
  password: string
  name?: string
  passwordHint?: string
  network?: string
}

export interface WalletAccount {
  chain: string
  address: string
  publicKey: string
  derivationPath?: string
  extPubKey?: string
}

export interface WalletResult {
  id: string
  source: string
  network: string
  mnemonic?: string
  keystoreJson: string
  accounts: Array<WalletAccount>
}
