/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function createWallet(input: CreateWalletInput): WalletResult

export interface CreateWalletInput {
  password: string
  name?: string
  passwordHint?: string
  network?: WalletNetwork
  entropy?: string
  derivations?: Array<DerivationInput>
}

export interface DerivationInput {
  chainId: string
  derivationPath?: string
  network?: WalletNetwork
}

export declare function deriveAccounts(input: DeriveAccountsInput): Array<WalletAccount>

export interface DeriveAccountsInput {
  keystoreJson: string
  password: string
  derivations?: Array<DerivationInput>
}

export declare function importWalletMnemonic(input: ImportWalletMnemonicInput): WalletResult

export interface ImportWalletMnemonicInput {
  mnemonic: string
  password: string
  name?: string
  passwordHint?: string
  network?: WalletNetwork
  derivations?: Array<DerivationInput>
}

export declare function importWalletPrivateKey(input: ImportWalletPrivateKeyInput): WalletResult

export interface ImportWalletPrivateKeyInput {
  privateKey: string
  password: string
  name?: string
  passwordHint?: string
  network?: WalletNetwork
  derivations?: Array<DerivationInput>
}

export declare function loadWallet(input: LoadWalletInput): WalletResult

export interface LoadWalletInput {
  keystoreJson: string
  password: string
  derivations?: Array<DerivationInput>
}

export interface WalletAccount {
  chainId: string
  address: string
  publicKey: string
  derivationPath?: string
  extPubKey?: string
}

export interface WalletMeta {
  id: string
  version: number
  sourceFingerprint: string
  source: WalletSource
  network: WalletNetwork
  name: string
  passwordHint?: string
  timestamp: number
  derivable: boolean
  curve?: string
  identifiedChainTypes?: Array<string>
}

export declare const enum WalletNetwork {
  Mainnet = 'MAINNET',
  Testnet = 'TESTNET',
}

export interface WalletResult {
  keystoreJson: string
  meta: WalletMeta
  accounts: Array<WalletAccount>
  mnemonic?: string
}

export declare const enum WalletSource {
  Wif = 'WIF',
  Private = 'PRIVATE',
  KeystoreV3 = 'KEYSTORE_V3',
  SubstrateKeystore = 'SUBSTRATE_KEYSTORE',
  Mnemonic = 'MNEMONIC',
  NewMnemonic = 'NEW_MNEMONIC',
}
