/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Creates a new mnemonic-backed wallet.
 *
 * If `entropy` is omitted, random 16-byte entropy is generated.
 * If `derivations` is omitted, default Ethereum and Tron accounts are derived
 * for the selected wallet network.
 */
export declare function createWallet(name: string, passphrase: string): WalletResult

/** A requested account derivation. */
export interface DerivationInput {
  /** CAIP-2 chain id, for example `eip155:1` or `tron:0x2b6653dc`. */
  chainId: string
  /** Derivation path to use for derivable wallets. */
  derivationPath?: string
  /** Network to use for this derivation. Defaults to the wallet network. */
  network?: WalletNetwork
}

/**
 * Derives accounts from a serialized keystore JSON in a single unlock flow.
 *
 * If `derivations` is omitted, default Ethereum and Tron accounts are derived
 * for the wallet network stored in the keystore.
 */
export declare function deriveAccounts(
  keystoreJson: string,
  password: string,
  derivations?: Array<DerivationInput> | undefined | null,
): Array<WalletAccount>

/** Ethereum access list item used for EIP-2930/EIP-1559 transactions. */
export interface EthAccessListItem {
  /** Accessed contract address. */
  address: string
  /** Accessed storage keys. */
  storageKeys: Array<string>
}

/** Ethereum message signing payload. */
export interface EthMessageInput {
  /** UTF-8 text or a hex string prefixed with `0x`. */
  message: string
  /** Signing mode. Defaults to `PERSONAL_SIGN`. */
  signatureType?: EthMessageSignatureType
}

/** Ethereum message signing mode. */
export declare const enum EthMessageSignatureType {
  /** Prefix with the `Ethereum Signed Message` header before hashing. */
  PersonalSign = 'PERSONAL_SIGN',
  /** Hash the raw payload bytes with keccak256 before signing. */
  EcSign = 'EC_SIGN',
}

/** Ethereum signed transaction result. */
export interface EthSignedTransaction {
  /** Serialized signed transaction payload. */
  signature: string
  /** Transaction hash. */
  txHash: string
}

/** Ethereum transaction signing payload. */
export interface EthTransactionInput {
  nonce: string
  gasPrice: string
  gasLimit: string
  to: string
  value: string
  data: string
  chainId: string
  txType: string
  maxFeePerGas: string
  maxPriorityFeePerGas: string
  accessList: Array<EthAccessListItem>
}

/**
 * Imports an existing mnemonic-backed wallet.
 *
 * If `derivations` is omitted, default Ethereum and Tron accounts are derived
 * for the selected wallet network.
 */
export declare function importWalletMnemonic(name: string, mnemonic: string, passphrase: string): WalletResult

/**
 * Imports a private key as a non-derivable wallet.
 *
 * If `derivations` is omitted, default Ethereum and Tron accounts are
 * returned. Derivation paths are ignored for non-derivable wallets.
 */
export declare function importWalletPrivateKey(name: string, privateKey: string, passphrase: string): WalletResult

/**
 * Loads a serialized keystore JSON and derives accounts from it.
 *
 * If `derivations` is omitted, default Ethereum and Tron accounts are derived
 * for the wallet network stored in the keystore.
 */
export declare function loadWallet(
  keystoreJson: string,
  password: string,
  derivations?: Array<DerivationInput> | undefined | null,
): WalletResult

/** Message signature returned to JavaScript. */
export interface SignedMessage {
  /** Hex-encoded recoverable signature. */
  signature: string
}

/**
 * Signs a plain chain-specific message using the default chain conventions.
 *
 * `chain_id` selects the signer implementation. Ethereum uses personal-sign
 * semantics, while Tron uses the default TRON message header and version.
 */
export declare function signMessage(
  keystoreJson: string,
  chainId: string,
  message: string,
  password: string,
): SignedMessage

/**
 * Signs an unsigned chain-specific transaction hex using the default chain
 * conventions.
 *
 * `chain_id` selects the signer implementation. Ethereum expects an unsigned
 * RLP-encoded transaction hex, while Tron expects raw transaction bytes hex.
 */
export declare function signTransaction(
  keystoreJson: string,
  chainId: string,
  txHex: string,
  password: string,
): EthSignedTransaction | TronSignedTransaction

/** Tron message signing payload. */
export interface TronMessageInput {
  /** UTF-8 text or a hex string prefixed with `0x`. */
  value: string
}

/** Tron signed transaction result. */
export interface TronSignedTransaction {
  /** Array of hex-encoded signatures. */
  signatures: Array<string>
}

/** Tron transaction signing payload. */
export interface TronTransactionInput {
  /** Hex-encoded raw transaction bytes. */
  rawData: string
}

/** A derived account returned to JavaScript. */
export interface WalletAccount {
  /** CAIP-2 chain id of the derived account. */
  chainId: string
  /** Chain-specific account address. */
  address: string
  /** Hex-encoded public key. */
  publicKey: string
  /** Derivation path used for this account when available. */
  derivationPath?: string
  /** Extended public key when supported by the wallet source. */
  extPubKey?: string
}

/** Wallet metadata exposed to JavaScript. */
export interface WalletMeta {
  /** Keystore identifier. */
  id: string
  /** Keystore version. */
  version: number
  /** Fingerprint of the original wallet source. */
  sourceFingerprint: string
  /** Source used to create or import the wallet. */
  source: WalletSource
  /** Wallet network stored in metadata. */
  network: WalletNetwork
  /** Wallet name stored in metadata. */
  name: string
  /** Optional password hint stored in metadata. */
  passwordHint?: string
  /** Metadata timestamp from the keystore. */
  timestamp: number
  /** Whether the wallet can derive child accounts from paths. */
  derivable: boolean
  /** Curve name when available. */
  curve?: string
  /** Optional chain types identified by the underlying keystore. */
  identifiedChainTypes?: Array<string>
}

/** Wallet network used for metadata and default account derivations. */
export declare const enum WalletNetwork {
  /** Production network defaults. */
  Mainnet = 'MAINNET',
  /** Test network defaults. */
  Testnet = 'TESTNET',
}

/** Wallet payload returned by create, import, and load operations. */
export interface WalletResult {
  /** Serialized keystore JSON. */
  keystoreJson: string
  /** Wallet metadata. */
  meta: WalletMeta
  /** Derived accounts requested for the operation. */
  accounts: Array<WalletAccount>
  /** Mnemonic phrase when creating or importing from mnemonic. */
  mnemonic?: string
}

/** Source used to create or import the wallet. */
export declare const enum WalletSource {
  /** Imported from WIF. */
  Wif = 'WIF',
  /** Imported from a raw private key. */
  Private = 'PRIVATE',
  /** Imported from a V3 keystore JSON payload. */
  KeystoreV3 = 'KEYSTORE_V3',
  /** Imported from a Substrate keystore payload. */
  SubstrateKeystore = 'SUBSTRATE_KEYSTORE',
  /** Imported from an existing mnemonic phrase. */
  Mnemonic = 'MNEMONIC',
  /** Created from a newly generated mnemonic phrase. */
  NewMnemonic = 'NEW_MNEMONIC',
}
