/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Cipher parameters for encryption. */
export interface CipherParams {
  /** Initialization vector (hex-encoded). */
  iv: string
}

/**
 * Creates a new mnemonic-backed wallet.
 *
 * The returned WalletInfo is also persisted under
 * `<vaultPath>/wallets/<wallet id>.json`. `index` selects the default derived
 * account index.
 */
export declare function createWallet(name: string, passphrase: string, vaultPath: string, index?: number | undefined | null): WalletInfo

/** Crypto section of the keystore containing encrypted private key. */
export interface CryptoData {
  /** Cipher algorithm name. */
  cipher: string
  /** Cipher parameters. */
  cipherparams: CipherParams
  /** Encrypted ciphertext (hex-encoded). */
  ciphertext: string
  /** KDF type name ("pbkdf2" or "scrypt"). */
  kdf: string
  /** KDF parameters serialized as the `kdfparams` field. */
  kdfparams: KdfParams
  /** Message authentication code (hex-encoded). */
  mac: string
}

/** Deletes a wallet from the vault by wallet id, exact name, or unique id prefix. */
export declare function deleteWallet(nameOrId: string, vaultPath: string): void

/** A requested account derivation. */
export interface DerivationInput {
  /** CAIP-2 chain id, for example `eip155:1` or `tron:0x2b6653dc`. */
  chainId: string
  /** Derivation path to use for derivable wallets. */
  derivationPath?: string
  /** Network to use for this derivation. Defaults to the wallet network. */
  network?: 'MAINNET' | 'TESTNET'
}

/**
 * Derives accounts from a serialized keystore JSON in a single unlock flow.
 *
 * If `derivations` is omitted, default Ethereum and Tron accounts are derived
 * for the wallet network stored in the keystore.
 */
export declare function deriveAccounts(keystoreJson: string, password: string, derivations?: Array<DerivationInput> | undefined | null): Array<WalletAccount>

/** Encrypted key pair containing encrypted string and nonce. */
export interface EncPairData {
  /** Encrypted string (hex-encoded). */
  encStr: string
  /** Nonce (hex-encoded). */
  nonce: string
}

/** Ethereum access list item used for EIP-2930/EIP-1559 transactions. */
export interface EthAccessListItem {
  /** Accessed contract address. */
  address: string
  /** Accessed storage keys. */
  storageKeys: Array<string>
}

/** Ethereum message signing payload. */
export interface EthMessageInput {
  /** UTF-8 text or a hex string prefixed with `0x`. */
  message: string
  /** Signing mode. Defaults to `PERSONAL_SIGN`. */
  signatureType?: EthMessageSignatureType
}

/** Ethereum message signing mode. */
export declare const enum EthMessageSignatureType {
  /** Prefix with the `Ethereum Signed Message` header before hashing. */
  PersonalSign = 'PERSONAL_SIGN',
  /** Hash the raw payload bytes with keccak256 before signing. */
  EcSign = 'EC_SIGN'
}

/** Ethereum signed transaction result. */
export interface EthSignedTransaction {
  /** Serialized signed transaction payload. */
  signature: string
  /** Transaction hash. */
  txHash: string
}

/** Ethereum transaction signing payload. */
export interface EthTransactionInput {
  nonce: string
  gasPrice: string
  gasLimit: string
  to: string
  value: string
  data: string
  chainId: string
  txType: string
  maxFeePerGas: string
  maxPriorityFeePerGas: string
  accessList: Array<EthAccessListItem>
}

/** Loads a persisted wallet from the vault by wallet id, exact name, or unique id prefix. */
export declare function getWallet(nameOrId: string, vaultPath: string): WalletInfo

/** Identity information for the keystore. */
export interface IdentityData {
  /** Encrypted authentication key. */
  encAuthKey: EncPairData
  /** Encryption key (hex-encoded). */
  encKey: string
  /** Identifier string. */
  identifier: string
  /** IPFS identifier. */
  ipfsId: string
}

/**
 * Imports a keystore JSON into the local vault under the provided wallet name.
 *
 * The wallet is renamed before persistence, then default or requested accounts
 * are derived in the same unlock flow.
 */
export declare function importWalletKeystore(name: string, keystoreJson: string, password: string, vaultPath: string, derivations?: Array<DerivationInput> | undefined | null): WalletInfo

/**
 * Imports an existing mnemonic-backed wallet.
 *
 * The returned WalletInfo is also persisted under
 * `<vaultPath>/wallets/<wallet id>.json`. `index` selects the default derived
 * account index.
 */
export declare function importWalletMnemonic(name: string, mnemonic: string, passphrase: string, vaultPath: string, index?: number | undefined | null): WalletInfo

/**
 * Imports a private key as a non-derivable wallet.
 *
 * The returned WalletInfo is also persisted under
 * `<vaultPath>/wallets/<wallet id>.json`. `index` is accepted for API parity
 * but ignored because private-key wallets are non-derivable.
 */
export declare function importWalletPrivateKey(name: string, privateKey: string, passphrase: string, vaultPath: string, index?: number | undefined | null): WalletInfo

/**
 * KDF parameters union type - can be either PBKDF2 or SCrypt.
 *
 * The fields present depend on the kdf type:
 * - PBKDF2: c, prf, dklen, salt
 * - SCrypt: n, p, r, dklen, salt
 */
export interface KdfParams {
  /** Iteration count (PBKDF2 only). */
  c?: number
  /** Pseudorandom function (PBKDF2 only). */
  prf?: string
  /** CPU/memory cost parameter (SCrypt only). */
  n?: number
  /** Parallelization parameter (SCrypt only). */
  p?: number
  /** Block size parameter (SCrypt only). */
  r?: number
  /** Derived key length. */
  dklen: number
  /** Salt (hex-encoded). */
  salt: string
}

/** Keystore data structure matching tcx-keystore Store. */
export interface KeystoreData {
  /** Keystore identifier (UUID). */
  id: string
  /** Keystore version number. */
  version: number
  /** Fingerprint of the wallet source. */
  sourceFingerprint: string
  /** Crypto section containing encrypted private key. */
  crypto: CryptoData
  /** Identity information. */
  identity: IdentityData
  /** Optional curve type. */
  curve?: string
  /** Encrypted original data (mnemonic or private key). */
  encOriginal: EncPairData
  /** Metadata. */
  imTokenMeta: KeystoreMetadata
}

/** Metadata stored in the keystore (imTokenMeta section). */
export interface KeystoreMetadata {
  /** Wallet name. */
  name: string
  /** Optional password hint. */
  passwordHint?: string
  /** Timestamp of keystore creation. */
  timestamp: number
  /** Source of the wallet (e.g., "MNEMONIC", "PRIVATE"). */
  source: 'WIF' | 'PRIVATE' | 'KEYSTORE_V3' | 'SUBSTRATE_KEYSTORE' | 'MNEMONIC' | 'NEW_MNEMONIC'
  /** Network type ("MAINNET" or "TESTNET"). */
  network: 'MAINNET' | 'TESTNET'
  /** Optional identified chain types. */
  identifiedChainTypes?: Array<string>
}

export declare function listWallet(vaultPath: string): Array<WalletInfo>

/**
 * Loads a serialized keystore JSON and derives accounts from it.
 *
 * If `derivations` is omitted, default Ethereum and Tron accounts are derived
 * for the wallet network stored in the keystore.
 */
export declare function loadWallet(keystoreJson: string, password: string, derivations?: Array<DerivationInput> | undefined | null): WalletInfo

/** Message signature returned to JavaScript. */
export interface SignedMessage {
  /** Hex-encoded recoverable signature. */
  signature: string
}

/**
 * Signs a plain chain-specific message using the default chain conventions.
 *
 * `chain_id` selects the signer implementation. Ethereum uses personal-sign
 * semantics, while Tron uses the default TRON message header and version.
 */
export declare function signMessage(name: string, chainId: string, message: string, password: string, vaultPath: string): SignedMessage

/**
 * Signs an unsigned chain-specific transaction hex using the default chain
 * conventions.
 *
 * `chain_id` selects the signer implementation. Ethereum expects an unsigned
 * RLP-encoded transaction hex, while Tron expects raw transaction bytes hex.
 */
export declare function signTransaction(name: string, chainId: string, txHex: string, password: string, vaultPath: string): EthSignedTransaction | TronSignedTransaction

/** Tron message signing payload. */
export interface TronMessageInput {
  /** UTF-8 text or a hex string prefixed with `0x`. */
  value: string
}

/** Tron signed transaction result. */
export interface TronSignedTransaction {
  /** Array of hex-encoded signatures. */
  signatures: Array<string>
}

/** Tron transaction signing payload. */
export interface TronTransactionInput {
  /** Hex-encoded raw transaction bytes. */
  rawData: string
}

/** A derived account returned to JavaScript. */
export interface WalletAccount {
  /** CAIP-2 chain id of the derived account. */
  chainId: string
  /** Chain-specific account address. */
  address: string
  /** Hex-encoded public key. */
  publicKey: string
  /** Derivation path used for this account when available. */
  derivationPath?: string
  /** Extended public key when supported by the wallet source. */
  extPubKey?: string
}

/** Wallet payload returned by create, import, and load operations. */
export interface WalletInfo {
  /** Wallet metadata. */
  meta: WalletMeta
  /** Keystore data object. */
  keystore: KeystoreData
  /** Derived accounts requested for the operation. */
  accounts: Array<WalletAccount>
}

/** Wallet metadata exposed to JavaScript. */
export interface WalletMeta {
  /** Keystore identifier. */
  id: string
  /** Keystore version. */
  version: number
  /** Fingerprint of the original wallet source. */
  sourceFingerprint: string
  /** Source used to create or import the wallet. */
  source: 'WIF' | 'PRIVATE' | 'KEYSTORE_V3' | 'SUBSTRATE_KEYSTORE' | 'MNEMONIC' | 'NEW_MNEMONIC'
  /** Wallet network stored in metadata. */
  network: 'MAINNET' | 'TESTNET'
  /** Wallet name stored in metadata. */
  name: string
  /** Optional password hint stored in metadata. */
  passwordHint?: string
  /** Metadata timestamp from the keystore. */
  timestamp: number
  /** Whether the wallet can derive child accounts from paths. */
  derivable: boolean
  /** Curve name when available. */
  curve?: string
  /** Optional chain types identified by the underlying keystore. */
  identifiedChainTypes?: Array<string>
}
