/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Cipher parameters for encryption. */
export interface CipherParams {
  /** Initialization vector (hex-encoded). */
  iv: string
}

/**
 * Creates a new mnemonic-backed wallet.
 *
 * If `vaultPath` is provided, the returned WalletInfo is also persisted under
 * that directory as `<wallet id>.json`. `index` selects the default derived
 * account index.
 */
export declare function createWallet(name: string, passphrase: string, vaultPath?: string | undefined | null, index?: number | undefined | null): WalletInfo

/** Crypto section of the keystore containing encrypted private key. */
export interface CryptoData {
  /** Cipher algorithm name. */
  cipher: string
  /** Cipher parameters. */
  cipherparams: CipherParams
  /** Encrypted ciphertext (hex-encoded). */
  ciphertext: string
  /** Key derivation function type and parameters. */
  kdfType: KdfType
  /** Message authentication code (hex-encoded). */
  mac: string
}

/** A requested account derivation. */
export interface DerivationInput {
  /** CAIP-2 chain id, for example `eip155:1` or `tron:0x2b6653dc`. */
  chainId: string
  /** Derivation path to use for derivable wallets. */
  derivationPath?: string
  /** Network to use for this derivation. Defaults to the wallet network. */
  network?: WalletNetwork
}

/**
 * Derives accounts from a serialized keystore JSON in a single unlock flow.
 *
 * If `derivations` is omitted, default Ethereum and Tron accounts are derived
 * for the wallet network stored in the keystore.
 */
export declare function deriveAccounts(keystoreJson: string, password: string, derivations?: Array<DerivationInput> | undefined | null): Array<WalletAccount>

/** Encrypted key pair containing encrypted string and nonce. */
export interface EncPairData {
  /** Encrypted string (hex-encoded). */
  encStr: string
  /** Nonce (hex-encoded). */
  nonce: string
}

/** Ethereum access list item used for EIP-2930/EIP-1559 transactions. */
export interface EthAccessListItem {
  /** Accessed contract address. */
  address: string
  /** Accessed storage keys. */
  storageKeys: Array<string>
}

/** Ethereum message signing payload. */
export interface EthMessageInput {
  /** UTF-8 text or a hex string prefixed with `0x`. */
  message: string
  /** Signing mode. Defaults to `PERSONAL_SIGN`. */
  signatureType?: EthMessageSignatureType
}

/** Ethereum message signing mode. */
export declare const enum EthMessageSignatureType {
  /** Prefix with the `Ethereum Signed Message` header before hashing. */
  PersonalSign = 'PERSONAL_SIGN',
  /** Hash the raw payload bytes with keccak256 before signing. */
  EcSign = 'EC_SIGN'
}

/** Ethereum signed transaction result. */
export interface EthSignedTransaction {
  /** Serialized signed transaction payload. */
  signature: string
  /** Transaction hash. */
  txHash: string
}

/** Ethereum transaction signing payload. */
export interface EthTransactionInput {
  nonce: string
  gasPrice: string
  gasLimit: string
  to: string
  value: string
  data: string
  chainId: string
  txType: string
  maxFeePerGas: string
  maxPriorityFeePerGas: string
  accessList: Array<EthAccessListItem>
}

/** Identity information for the keystore. */
export interface IdentityData {
  /** Encrypted authentication key. */
  encAuthKey: EncPairData
  /** Encryption key (hex-encoded). */
  encKey: string
  /** Identifier string. */
  identifier: string
  /** IPFS identifier. */
  ipfsId: string
}

/**
 * Imports an existing mnemonic-backed wallet.
 *
 * If `vaultPath` is provided, the returned WalletInfo is also persisted under
 * that directory as `<wallet id>.json`. `index` selects the default derived
 * account index.
 */
export declare function importWalletMnemonic(name: string, mnemonic: string, passphrase: string, vaultPath?: string | undefined | null, index?: number | undefined | null): WalletInfo

/**
 * Imports a private key as a non-derivable wallet.
 *
 * If `vaultPath` is provided, the returned WalletInfo is also persisted under
 * that directory as `<wallet id>.json`. `index` is accepted for API parity but
 * ignored because private-key wallets are non-derivable.
 */
export declare function importWalletPrivateKey(name: string, privateKey: string, passphrase: string, vaultPath?: string | undefined | null, index?: number | undefined | null): WalletInfo

/** Key derivation function type and parameters. */
export interface KdfType {
  /** KDF type name ("pbkdf2" or "scrypt"). */
  kdf: string
  /** PBKDF2 parameters (if kdf is "pbkdf2"). */
  kdfparams?: Pbkdf2Params
  /** SCrypt parameters (if kdf is "scrypt"). */
  scryptParams?: SCryptParams
}

/** Keystore data structure matching tcx-keystore Store. */
export interface KeystoreData {
  /** Keystore identifier (UUID). */
  id: string
  /** Keystore version number. */
  version: number
  /** Fingerprint of the wallet source. */
  sourceFingerprint: string
  /** Crypto section containing encrypted private key. */
  crypto: CryptoData
  /** Identity information. */
  identity: IdentityData
  /** Optional curve type. */
  curve?: string
  /** Encrypted original data (mnemonic or private key). */
  encOriginal: EncPairData
  /** Metadata. */
  imTokenMeta: KeystoreMetadata
}

/** Metadata stored in the keystore (imTokenMeta section). */
export interface KeystoreMetadata {
  /** Wallet name. */
  name: string
  /** Optional password hint. */
  passwordHint?: string
  /** Timestamp of keystore creation. */
  timestamp: number
  /** Source of the wallet (e.g., "MNEMONIC", "PRIVATE"). */
  source: string
  /** Network type ("MAINNET" or "TESTNET"). */
  network: string
  /** Optional identified chain types. */
  identifiedChainTypes?: Array<string>
}

export declare function listWallet(vaultPathOpt?: string | undefined | null): Array<WalletInfo>

/**
 * Loads a serialized keystore JSON and derives accounts from it.
 *
 * If `derivations` is omitted, default Ethereum and Tron accounts are derived
 * for the wallet network stored in the keystore.
 */
export declare function loadWallet(keystoreJson: string, password: string, derivations?: Array<DerivationInput> | undefined | null): WalletInfo

/** PBKDF2 key derivation function parameters. */
export interface Pbkdf2Params {
  /** Iteration count. */
  c: number
  /** Pseudorandom function. */
  prf: string
  /** Derived key length. */
  dklen: number
  /** Salt (hex-encoded). */
  salt: string
}

/** SCrypt key derivation function parameters. */
export interface SCryptParams {
  /** CPU/memory cost parameter. */
  n: number
  /** Parallelization parameter. */
  p: number
  /** Block size parameter. */
  r: number
  /** Derived key length. */
  dklen: number
  /** Salt (hex-encoded). */
  salt: string
}

/** Message signature returned to JavaScript. */
export interface SignedMessage {
  /** Hex-encoded recoverable signature. */
  signature: string
}

/**
 * Signs a plain chain-specific message using the default chain conventions.
 *
 * `chain_id` selects the signer implementation. Ethereum uses personal-sign
 * semantics, while Tron uses the default TRON message header and version.
 */
export declare function signMessage(keystoreJson: string, chainId: string, message: string, password: string): SignedMessage

/**
 * Signs an unsigned chain-specific transaction hex using the default chain
 * conventions.
 *
 * `chain_id` selects the signer implementation. Ethereum expects an unsigned
 * RLP-encoded transaction hex, while Tron expects raw transaction bytes hex.
 */
export declare function signTransaction(keystoreJson: string, chainId: string, txHex: string, password: string): EthSignedTransaction | TronSignedTransaction

/** Tron message signing payload. */
export interface TronMessageInput {
  /** UTF-8 text or a hex string prefixed with `0x`. */
  value: string
}

/** Tron signed transaction result. */
export interface TronSignedTransaction {
  /** Array of hex-encoded signatures. */
  signatures: Array<string>
}

/** Tron transaction signing payload. */
export interface TronTransactionInput {
  /** Hex-encoded raw transaction bytes. */
  rawData: string
}

/** A derived account returned to JavaScript. */
export interface WalletAccount {
  /** CAIP-2 chain id of the derived account. */
  chainId: string
  /** Chain-specific account address. */
  address: string
  /** Hex-encoded public key. */
  publicKey: string
  /** Derivation path used for this account when available. */
  derivationPath?: string
  /** Extended public key when supported by the wallet source. */
  extPubKey?: string
}

/** Wallet payload returned by create, import, and load operations. */
export interface WalletInfo {
  /** Keystore data object. */
  keystore: KeystoreData
  /** Wallet metadata. */
  meta: WalletMeta
  /** Derived accounts requested for the operation. */
  accounts: Array<WalletAccount>
}

/** Wallet metadata exposed to JavaScript. */
export interface WalletMeta {
  /** Keystore identifier. */
  id: string
  /** Keystore version. */
  version: number
  /** Fingerprint of the original wallet source. */
  sourceFingerprint: string
  /** Source used to create or import the wallet. */
  source: WalletSource
  /** Wallet network stored in metadata. */
  network: WalletNetwork
  /** Wallet name stored in metadata. */
  name: string
  /** Optional password hint stored in metadata. */
  passwordHint?: string
  /** Metadata timestamp from the keystore. */
  timestamp: number
  /** Whether the wallet can derive child accounts from paths. */
  derivable: boolean
  /** Curve name when available. */
  curve?: string
  /** Optional chain types identified by the underlying keystore. */
  identifiedChainTypes?: Array<string>
}

/** Wallet network used for metadata and default account derivations. */
export declare const enum WalletNetwork {
  /** Production network defaults. */
  Mainnet = 'MAINNET',
  /** Test network defaults. */
  Testnet = 'TESTNET'
}

/** Source used to create or import the wallet. */
export declare const enum WalletSource {
  /** Imported from WIF. */
  Wif = 'WIF',
  /** Imported from a raw private key. */
  Private = 'PRIVATE',
  /** Imported from a V3 keystore JSON payload. */
  KeystoreV3 = 'KEYSTORE_V3',
  /** Imported from a Substrate keystore payload. */
  SubstrateKeystore = 'SUBSTRATE_KEYSTORE',
  /** Imported from an existing mnemonic phrase. */
  Mnemonic = 'MNEMONIC',
  /** Created from a newly generated mnemonic phrase. */
  NewMnemonic = 'NEW_MNEMONIC'
}
