/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Public API key metadata exposed to JavaScript. */
export interface ApiKeyInfo {
  /** Stable API key identifier. */
  id: string
  /** Human-friendly key name. */
  name: string
  /** API key schema version. */
  version: number
  /** Creation time in Unix seconds. */
  createdAt: number
  /** Bound wallet ids. */
  walletIds: Array<string>
  /** Attached policy ids evaluated during agent-mode signing. */
  policyIds: Array<string>
  /** Optional expiry time in Unix seconds for the key itself. */
  expiresAt?: number
}

/** Cipher parameters for encryption. */
export interface CipherParams {
  /** Initialization vector (hex-encoded). */
  iv: string
}

/** Creates an API key bound to one or more wallets and optional declarative policies. */
export declare function createApiKey(name: string, walletIds: Array<string>, policyIds: Array<string>, passphrase: string, expiresAt?: number, vaultPathOpt?: string): CreatedApiKey

/** Result returned when an API key is created. */
export interface CreatedApiKey {
  /** Key file id for marking the API key file. */
  id: string
  /** Public API key metadata. */
  apiKey: ApiKeyInfo
  /** Token returned once at creation time. */
  token: string
}

/** Creates and persists a declarative policy definition. */
export declare function createPolicy(input: PolicyCreateInput, vaultPath: string): PolicyInfo

/**
 * Creates a new mnemonic-backed wallet.
 *
 * The returned WalletInfo is also persisted under
 * `<vaultPath>/wallets/<wallet id>.json`. `index` selects the default derived
 * account index.
 */
export declare function createWallet(name: string, passphrase: string, vaultPath: string, index?: number | undefined | null): WalletInfo

/** Crypto section of the keystore containing encrypted private key. */
export interface CryptoData {
  /** Cipher algorithm name. */
  cipher: string
  /** Cipher parameters. */
  cipherparams: CipherParams
  /** Encrypted ciphertext (hex-encoded). */
  ciphertext: string
  /** KDF type name ("pbkdf2" or "scrypt"). */
  kdf: string
  /** KDF parameters serialized as the `kdfparams` field. */
  kdfparams: KdfParams
  /** Message authentication code (hex-encoded). */
  mac: string
}

/** Deletes a policy if no API key still references it. */
export declare function deletePolicy(nameOrId: string, vaultPath: string): void

/** Deletes a wallet from the vault by wallet id, exact name, or unique id prefix. */
export declare function deleteWallet(nameOrId: string, vaultPath: string): void

/** A requested account derivation. */
export interface DerivationInput {
  /** CAIP-2 chain id, for example `eip155:1` or `tron:0x2b6653dc`. */
  chainId: string
  /** Derivation path to use for derivable wallets. */
  derivationPath?: string
}

/**
 * Derives accounts from a serialized keystore JSON in a single unlock flow.
 *
 * If `derivations` is omitted, default Ethereum and Tron accounts are derived
 * for the wallet network stored in the keystore.
 */
export declare function deriveAccounts(keystoreJson: string, password: string, derivations?: Array<DerivationInput> | undefined | null): Array<WalletAccount>

/** Encrypted key pair containing encrypted string and nonce. */
export interface EncPairData {
  /** Encrypted string (hex-encoded). */
  encStr: string
  /** Nonce (hex-encoded). */
  nonce: string
}

/**
 * Exports the wallet's mnemonic or private key.
 *
 * Returns the mnemonic phrase for HD wallets or the private key for private key wallets.
 * Requires the wallet passphrase to decrypt the keystore.
 */
export declare function exportWallet(nameOrId: string, password: string, vaultPath: string): string

/** Loads a persisted API key by key id, exact name, or unique id prefix. */
export declare function getApiKey(nameOrId: string, vaultPath: string): ApiKeyInfo

/** Loads a persisted policy by policy id, exact name, or unique id prefix. */
export declare function getPolicy(nameOrId: string, vaultPath: string): PolicyInfo

/** Loads a persisted wallet from the vault by wallet id, exact name, or unique id prefix. */
export declare function getWallet(nameOrId: string, vaultPath: string): WalletInfo

/** Identity information for the keystore. */
export interface IdentityData {
  /** Encrypted authentication key. */
  encAuthKey: EncPairData
  /** Encryption key (hex-encoded). */
  encKey: string
  /** Identifier string. */
  identifier: string
  /** IPFS identifier. */
  ipfsId: string
}

/**
 * Imports a keystore JSON into the local vault under the provided wallet name.
 *
 * The wallet is renamed before persistence, then default or requested accounts
 * are derived in the same unlock flow.
 */
export declare function importWalletKeystore(name: string, keystoreJson: string, password: string, vaultPath: string, derivations?: Array<DerivationInput> | undefined | null): WalletInfo

/**
 * Imports an existing mnemonic-backed wallet.
 *
 * The returned WalletInfo is also persisted under
 * `<vaultPath>/wallets/<wallet id>.json`. `index` selects the default derived
 * account index.
 */
export declare function importWalletMnemonic(name: string, mnemonic: string, passphrase: string, vaultPath: string, index?: number | undefined | null): WalletInfo

/**
 * Imports a private key as a non-derivable wallet.
 *
 * The returned WalletInfo is also persisted under
 * `<vaultPath>/wallets/<wallet id>.json`. `index` is accepted for API parity
 * but ignored because private-key wallets are non-derivable.
 */
export declare function importWalletPrivateKey(name: string, privateKey: string, passphrase: string, vaultPath: string, index?: number | undefined | null): WalletInfo

/**
 * KDF parameters union type - can be either PBKDF2 or SCrypt.
 *
 * The fields present depend on the kdf type:
 * - PBKDF2: c, prf, dklen, salt
 * - SCrypt: n, p, r, dklen, salt
 */
export interface KdfParams {
  /** Iteration count (PBKDF2 only). */
  c?: number
  /** Pseudorandom function (PBKDF2 only). */
  prf?: string
  /** CPU/memory cost parameter (SCrypt only). */
  n?: number
  /** Parallelization parameter (SCrypt only). */
  p?: number
  /** Block size parameter (SCrypt only). */
  r?: number
  /** Derived key length. */
  dklen: number
  /** Salt (hex-encoded). */
  salt: string
}

/** Keystore data structure matching tcx-keystore Store. */
export interface KeystoreData {
  /** Keystore identifier (UUID). */
  id: string
  /** Keystore version number. */
  version: number
  /** Fingerprint of the wallet source. */
  sourceFingerprint: string
  /** Crypto section containing encrypted private key. */
  crypto: CryptoData
  /** Identity information. */
  identity: IdentityData
  /** Optional curve type. */
  curve?: string
  /** Encrypted original data (mnemonic or private key). */
  encOriginal: EncPairData
  /** Metadata. */
  imTokenMeta: KeystoreMetadata
}

/** Metadata stored in the keystore (imTokenMeta section). */
export interface KeystoreMetadata {
  /** Wallet name. */
  name: string
  /** Optional password hint. */
  passwordHint?: string
  /** Timestamp of keystore creation. */
  timestamp: number
  /** Source of the wallet (e.g., "MNEMONIC", "PRIVATE"). */
  source: 'WIF' | 'PRIVATE' | 'KEYSTORE_V3' | 'SUBSTRATE_KEYSTORE' | 'MNEMONIC' | 'NEW_MNEMONIC'
  /** Optional identified chain types. */
  identifiedChainTypes?: Array<string>
}

/** Lists all persisted API keys in the vault. */
export declare function listApiKey(vaultPath: string): Array<ApiKeyInfo>

/** Lists all persisted policies in the vault. */
export declare function listPolicy(vaultPath: string): Array<PolicyInfo>

export declare function listWallet(vaultPath: string): Array<WalletInfo>

/**
 * Loads a serialized keystore JSON and derives accounts from it.
 *
 * If `derivations` is omitted, default Ethereum and Tron accounts are derived
 * for the wallet network stored in the keystore.
 */
export declare function loadWallet(keystoreJson: string, password: string, derivations?: Array<DerivationInput> | undefined | null): WalletInfo

/** Input used to create a policy definition. */
export interface PolicyCreateInput {
  /** Human-friendly policy name. */
  name: string
  /** Declarative rules that must all pass during agent-mode signing. */
  rules: Array<PolicyRule>
}

/** Persisted declarative policy definition. */
export interface PolicyInfo {
  /** Stable policy identifier. */
  id: string
  /** Human-friendly policy name. */
  name: string
  /** Policy record schema version. */
  version: number
  /** Creation time in Unix seconds. */
  createdAt: number
  /** Declarative rules evaluated for this policy. */
  rules: Array<PolicyRule>
  /** Policy action. v1 always uses `deny`. */
  action: string
}

/** Declarative policy rule used during agent-mode signing. */
export interface PolicyRule {
  /** Rule type. Supported values are `allowed_chains` and `expires_at`. */
  type: string
  /** Allowed CAIP-2 chain ids for `allowed_chains`. */
  chainIds?: Array<string>
  /** Unix seconds timestamp for `expires_at`. */
  timestamp?: number
}

/** Revokes an API key by removing its persisted record from the vault. */
export declare function revokeApiKey(nameOrId: string, vaultPath: string): void

/** Message signature returned to JavaScript. */
export interface SignedMessage {
  /** Hex-encoded recoverable signature. */
  signature: string
}

/** Unified signed transaction result. */
export interface SignedTransactionResult {
  /** Hex-encoded recoverable signature (65 bytes). */
  signature: string
}

/**
 * Signs a plain chain-specific message using the default chain conventions.
 *
 * `chain_id` selects the signer implementation. Ethereum uses personal-sign
 * semantics, while Tron uses the default TRON message header and version.
 * `credential` accepts either the wallet passphrase (owner mode) or a
 * `bulu_key_...` API token (agent mode).
 */
export declare function signMessage(name: string, chainId: string, message: string, credential: string, vaultPath: string): SignedMessage

/**
 * Signs an unsigned chain-specific transaction hex using the default chain
 * conventions.
 *
 * `chain_id` selects the signer implementation. Ethereum expects an unsigned
 * RLP-encoded transaction hex, while Tron expects raw transaction bytes hex.
 * `credential` accepts either the wallet passphrase (owner mode) or a
 * `bulu_key_...` API token (agent mode).
 */
export declare function signTransaction(name: string, chainId: string, txHex: string, credential: string, vaultPath: string): SignedTransactionResult

/** A derived account returned to JavaScript. */
export interface WalletAccount {
  /** CAIP-2 chain id of the derived account. */
  chainId: string
  /** Stable account identifier in the form `<chain_id>:<address>`. */
  accountId: string
  /** Chain-specific account address. */
  address: string
  /** Derivation path used for this account, or an empty string when unavailable. */
  derivationPath: string
}

/** Wallet payload returned by create, import, and load operations. */
export interface WalletInfo {
  /** Wallet metadata. */
  meta: WalletMeta
  /** Keystore data object. */
  keystore: KeystoreData
  /** Derived accounts requested for the operation. */
  accounts: Array<WalletAccount>
}

/** Wallet metadata exposed to JavaScript. */
export interface WalletMeta {
  /** Keystore identifier. */
  id: string
  /** Keystore version. */
  version: number
  /** Fingerprint of the original wallet source. */
  sourceFingerprint: string
  /** Source used to create or import the wallet. */
  source: 'WIF' | 'PRIVATE' | 'KEYSTORE_V3' | 'SUBSTRATE_KEYSTORE' | 'MNEMONIC' | 'NEW_MNEMONIC'
  /** Wallet name stored in metadata. */
  name: string
  /** Optional password hint stored in metadata. */
  passwordHint?: string
  /** Metadata timestamp from the keystore. */
  timestamp: number
  /** Whether the wallet can derive child accounts from paths. */
  derivable: boolean
  /** Curve name when available. */
  curve?: string
  /** Optional chain types identified by the underlying keystore. */
  identifiedChainTypes?: Array<string>
}
