name: Setup Node and pnpm
description: Setup pnpm and Node.js with pnpm cache enabled.
inputs:
  node-version:
    description: Node.js version to install.
    required: false
    default: '24'
  architecture:
    description: Optional Node.js architecture.
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v5

    - name: Setup node
      if: ${{ inputs.architecture == '' }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: 'https://registry.npmjs.org/'

    - name: Setup node with architecture
      if: ${{ inputs.architecture != '' }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: 'https://registry.npmjs.org/'
        architecture: ${{ inputs.architecture }}
